# Generated by Django 2.2.3 on 2019-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=20, verbose_name='关键词')),
            ],
        ),
    ]
